# This file does not define "services" per se.
# Rather, the following entries define docker
# images, and not containers.
#
# This allows us to use `docker-compose` to
# build them. See the `Makefile`.

version: "3.7"

services:

  ubuntu-bionic:
    image: ubuntu:bionic
    build:
      context: .
      dockerfile: debian.Dockerfile
      args:
        OS: ubuntu
        FLAVOR: bionic
        TIMEZONE: "America/Chicago"
        LOCALE: "en_US.UTF-8"

  ubuntu-xenial:
    image: ubuntu:xenial
    build:
      context: .
      dockerfile: debian.Dockerfile
      args:
        OS: ubuntu
        FLAVOR: xenial
        TIMEZONE: "America/Chicago"
        LOCALE: "en_US.UTF-8"

  debian-buster:
    image: debian:buster
    build:
      context: .
      dockerfile: debian.Dockerfile
      args:
        OS: debian
        FLAVOR: buster
        TIMEZONE: "America/Chicago"
        LOCALE: "en_US.UTF-8"


  rust-1.34.0-llvm-8-ubuntu-bionic:
    image: rust:1.34.0-llvm-8-ubuntu-bionic
    build:
      context: .
      dockerfile: rust-debian.Dockerfile
      args:
        OS: ubuntu
        FLAVOR: bionic
        LLVM_VERSION: 8
        RUST_VERSION: 1.34.0

  z3-4.6.0-llvm-8-ubuntu-bionic:
    image: z3:4.6.0-llvm-8-ubuntu-bionic
    build:
      context: .
      dockerfile: z3-debian.Dockerfile
      args:
        OS: ubuntu
        FLAVOR: bionic
        LLVM_VERSION: 8
        Z3_VERSION: 4.6.0

  haskell-ubuntu-bionic:
    image: haskell:ubuntu-bionic
    build:
      context: .
      dockerfile: haskell-debian.Dockerfile
      args:
        OS: ubuntu
        FLAVOR: bionic
